### ISSUE TITLE
website dark-mode broken. ?

### ISSUE THREAD

**Issue by weepy** [sidharth-anand/teil-ui#2]
I'm looking at https://sidharth-anand.github.io/teil-ui/docs/getting-started/introduction on macos chrome and its all dark backgorund and dark font. 
<img width="1200" alt="Screenshot 2023-02-01 at 15 21 28" src="https://user-images.githubusercontent.com/820/216068653-194ca199-9e85-4aab-8f1e-74b1fdd44031.png">

**Comment by sidharth-anand** [comment]
Can you confirm if it works now?

**Comment by weepy** [comment]
yep!
